### ISSUE TITLE
Utilize site icon customizer option for PWA icon

### ISSUE THREAD

**Issue by pradeep910** [rtCamp/pwa-extension#1]
Current code asks for separate `/assets/img/icon-%2$sx%2$s.png` inside theme. We can utilize site icon itself to generate app icon sizes. 

Goal is to make manifest file ready for all WordPress sites, and with just site icon add-to-homescreen feature can be enabled. 

- [x] Use site icon to generate PWA app icon sizes - https://github.com/rtCamp/pwa-extension/blob/master/class-pwa-manifest.php#L32-L35
- [ ] Add filter for App Icon URLs so that we can filter Icon URLs if needed.

**Comment by pradeep910** [comment]
@deepaklalwani97 Please work on this and add filter for icons. 

- [ ]  Add filter for App Icon URLs so that we can filter Icon URLs if needed.

**Comment by deepaklalwani97** [comment]
@pradeep910 I have added filter for app icon URLs in this PR https://github.com/rtCamp/pwa-extension/pull/23, please review

**Comment by deepaklalwani97** [comment]
@pradeep910 We can change icon URL using the `web_app_manifest` filter. Let me know if we still need this refer https://github.com/rtCamp/pwa-extension/pull/23#discussion_r369492168. Otherwise, we can close this
