### ISSUE TITLE
[PWA] Precache site assets and current page

### ISSUE THREAD

**Issue by pradeep910** [rtCamp/pwa-extension#14]
## Precaching for site assets and homepage URL

Since first page load is not storing the cache offline, as a result after first page load, if internet goes off, first page load will not be loaded offline even when it was accessed fully. 
We should try adding current page to the precache. 

To explain the problem - 

**1st page load -** 
![Screenshot 2019-12-27 at 12 39 41 PM](https://user-images.githubusercontent.com/1139853/71506205-fc8c7600-28a5-11ea-8785-d26327b735ea.png)

**2nd page load (reloading homepage or accessing precached pages) -** 
![Screenshot 2019-12-27 at 12 40 31 PM](https://user-images.githubusercontent.com/1139853/71506264-41b0a800-28a6-11ea-8df0-f024aed41f9b.png)

**3rd page load (making network request. ie. accessing page which was not precached earlier) -**
![Screenshot 2019-12-27 at 12 41 06 PM](https://user-images.githubusercontent.com/1139853/71506293-6573ee00-28a6-11ea-8a10-6ca6706af657.png)

Current page can be anything like homepage or contact page, depending on users first landing page from organic search.

1. Site assets - such as *.css, *.js including workbox library -                 
> https://rtcamp-v9.dev3.rt.gw/wp-content/plugins/pwa/wp-includes/js/workbox/workbox-strategies.dev.js

2. Current page - users first page load.

Ideally function like this should solve first page load issue.

```add_action( 'wp_front_service_worker', function( \WP_Service_Worker_Scripts $scripts ) {
        $scripts->precaching_routes()->register(
                'https://rtcamp-v9.dev3.rt.gw/wp-content/plugins/pwa/wp-includes/js/workbox/workbox-strategies.dev.js',
                array(
                        'revision' => get_bloginfo( 'version' ),
                )
        );   
} );
```

@chandrapatel 
We should probably add an option to select theme or other assets to add to precache list like this - https://github.com/xwp/pwa-wp/issues/25#issuecomment-408645007
![screenshot](https://user-images.githubusercontent.com/134745/43361856-09be66e6-9291-11e8-8384-953b09b4433d.png)

**Comment by chandrapatel** [comment]
@pradeep910 Check below plugin by Weston Ruter for basic site caching including cache theme assets.

https://gist.github.com/westonruter/1a63d052beb579842461f6ad837715fb 

Also, check this issue https://github.com/xwp/pwa-wp/issues/180 for homepage not cached.

**Comment by DevikVekariya** [comment]
@pradeep910 @chandrapatel Any work remaining here? else please close the issue.

posting as a copy of slack message - https://rtcamp.slack.com/archives/CQT8TKCJW/p1579585337046500?thread_ts=1579585030.046200&cid=CQT8TKCJW
