### ISSUE TITLE
Setup and add unit test cases

### ISSUE THREAD

**Issue by deepaklalwani97** [rtCamp/pwa-extension#19]
- Create a setup for Php Unit Tests along with the documentation.

Acceptance Criteria:

- Each class and its method should pass though the Php Unit test case
- If any of the methods is ignored then, it should have proper docs with a reason to ignore it.
- It should have detailed documentation for the local setup of Unit tests and how to run it locally.

**Comment by DevikVekariya** [comment]
@deepaklalwani97 

Please add your estimate here for this issue.

You need to add the detailed desc for the work done on a day either on AC time entry description or GH issue that you are working on.

**Comment by DevikVekariya** [comment]
@deepaklalwani97 @kiranpotphode 

Let's do collaborative work here.

Anyone can pick the Unit Testing setup from here and merge it to the repo, so it can have common base to start with - https://github.com/rtCamp/wp-google-login/pull/19

Then pick the classes and post a comment here that you are picking this class. So another folk can pick the next class to start with.

This will speed up the work and it will help speed it up. 

Do follow the peer reviews for the PRs to make it more similar between your work

**Comment by DevikVekariya** [comment]
Please create all these PRs against the `dev-unit-test` (create from master) branch. Make sure that we'll have one PR from `dev-unit-test` to master for all together

**Comment by deepaklalwani97** [comment]
@DevikVekariya I have already written 2 out of 3 tests for the classes. I am working on third class and facing some issue loading the depending plugin in the test environment so this issue might take 4-5 more hours approx.

**Comment by deepaklalwani97** [comment]
@DevikVekariya Can you help me with the GH_bot_token and vault_token for this repository I do not have access and not sure how to generate it.

**Comment by deepaklalwani97** [comment]
@DevikVekariya The PHPCS and PHPUnit actions are set up and running.

**Comment by DevikVekariya** [comment]
@deepaklalwani97 @kiranpotphode 

 Please schedule merging this PR tomorrow. https://github.com/rtCamp/pwa-extension/pull/20

@sagarnasit please help test one time.

**Comment by sagarnasit** [comment]
@deepaklalwani97 What are the steps needed for add to home screen? I followed readme for adding icon in theme but it didn't work for me.

**Comment by deepaklalwani97** [comment]
The add to home screen does not work with our dev sites because of Http auth the web app manifest throws 401 error so I have tested this on different 000host site.

**Comment by sagarnasit** [comment]
@deepaklalwani97 Can you add proper readme for `add to home screen` feature. If it require manifest file then please mention steps for that. Different device may support different size icons there for please mention that too or you can provide link for detailed references.

**Comment by deepaklalwani97** [comment]
@sagarnasit The add to the home screen just needs the icon to be present in the theme directory which is already specified in readme. The PWA plugin already creates the manifest file we do not need to create a manifest file.

**Comment by deepaklalwani97** [comment]
@sagarnasit Is this #26 tested from your side. Can we merge this now? Please confirm.

**Comment by DevikVekariya** [comment]
Why https://github.com/rtCamp/pwa-extension/pull/26 has to be tested by sagar? @deepaklalwani97

**Comment by deepaklalwani97** [comment]
@DevikVekariya It is tested from my side to just asking @sagarnasit to confirm.

**Comment by deepaklalwani97** [comment]
@DevikVekariya As the offline form is in a separate issue and there is no update needed in this PR we can merge it or get it tested by QA.

**Comment by pooja-muchandikar** [comment]
@deepaklalwani97 

Tested the Add to Screen and Offline reading feature and it works as expected. 

On mobile device Add to Homescreen option was visible and the visited pages are also getting cached.

On desktop an `+` icon was shown in the address bar checked installing the app through it and checked the offline reading feature and it works. Also, only the visited pages are available for offline reading.

**Comment by deepaklalwani97** [comment]
Closing this issue as the unit tests are merged to the master.
