### ISSUE TITLE
Navigation preload is continuously reloading when offline

### ISSUE THREAD

**Issue by pradeep910** [rtCamp/pwa-extension#21]
When offline, the webpage reloads continuously, maybe due to service worker navigation preload. Please fix it.

**Comment by sagarnasit** [comment]
@pradeep910 Tested for this issue on the labs demo site. Also tested offline commenting and form submission. Working fine as expected. Let me know the reproduction steps if you face this issue again.

**Comment by DevikVekariya** [comment]
Keeping track of this issue here => https://github.com/rtCamp/labs/issues/10

Closing this as seems a duplicate issue.
