### ISSUE TITLE
Conflicts with iZooto plugin

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/pwa-extension#33]
```
Test Environment:
Plugins active:
Official PWA plugin: v0.3.0
rt PWA Extension: v1.0.2
iZooto plugin: v3.6.6
```
1. Offline reading is working in mobile :heavy_check_mark: and while checking in desktop :heavy_multiplication_x: faced errors in the console. Please check the screenshot.
![Screenshot from 2020-03-09 10-33-04](https://user-images.githubusercontent.com/41000648/76216512-b99c3680-6236-11ea-8b0a-85be026c6621.png)

2. Add to Home Screen - Add to home screen option was not visible in mobile :heavy_multiplication_x: . On desktop the install option is shown on the browser bar :heavy_check_mark: . On mobile tried clearing cache but still the add to home screen option was not visible. Note: http auth is been removed from the site 

3. iZooto Push Notifications - Push notifications are working in both mobile and desktop. Created Post and enabled notification option on post publish/update notifications are triggered on mobile and desktop. 

**Note: 
The above 1st and 2nd issues occurs when iZooto pluign is enabled. If this plugin is disabled then above mentioned issues works fine.
iZooto plugin is creating conflicts with the other features, offline reading and Add to Home screen.**

**Comment by deepaklalwani97** [comment]
@sagarnasit I have checked the conflict that is being created by offline form submission script. when the routes for forms are missing in the settings the random string is generated as a form route which is causing the page to reload continuously. Can we allow offline form submission only for the routes defined in the plugin settings and include offline-form script when the routes are defined?

**Comment by deepaklalwani97** [comment]
@juhi123 The PR for this issue is merged to develop and the `develop` branch needs QA testing.  Follow readme and test the `develop` branch let me know in case of queries or you face any issue.

**Comment by juhi123** [comment]
@deepaklalwani97 Thanks for the update, I will post the status by EOD

**Comment by juhi123** [comment]
@deepaklalwani97 The Gravity form plugin we have is 2.4.11, shouldn't we test it with the latest one? Version 2.4.17 is available, let me know how I can get?

**Comment by juhi123** [comment]
@deepaklalwani97 I have tested with the latest gravity form. Everything worked, except offline form submission didn't work with firefox, can you please try at your end.

**Comment by deepaklalwani97** [comment]
@juhi123 Sometimes for some reason the sync fails when the device is online and the retry for sync is executed after 5 mins can you try and check after some time.

**Comment by juhi123** [comment]
@deepaklalwani97 Yeah you are right, thanks. All test cases seem to be working fine 👍

**Comment by deepaklalwani97** [comment]
@juhi123 A new version of WordPress and PWA plugin is now available. I have self-tested the develop branch with the latest PWA plugin and WordPress version. Please follow the readme and test develop branch with the latest version of the WordPress and PWA plugin to check the compatibility before releasing the plugin.
