### ISSUE TITLE
Gravity form submission does not work if the current form URL is added in the menu

### ISSUE THREAD

**Issue by deepaklalwani97** [rtCamp/pwa-extension#41]
Tracking this https://github.com/rtCamp/pwa-extension/pull/18#issuecomment-609707217 here

The Gravity form submission does not work if the form page is part of the menu. When the menu precache tries to precache the form URL the does not submit and just redirects to the current page.

Version: 1.0.3(Develop)

Ways to reproduce: 
1) Create a page with gravity form.
2) Add page to the menu 
3) Try to submit the gravity form on that page it will redirect to the same page.
4) Remove the page from the menu and the submission works fine for that form.

**Comment by deepaklalwani97** [comment]
@pradeep910 Should we remove the menu precaching as with the new version of the PWA plugin it is creating conflict with the gravity form submission. I've checked and there is no way we can selectively remove any link from caching because we cannot get the requested URL in the `wp_front_service_worker` hook.

**Comment by pradeep910** [comment]
Yes we can remove it.

**Comment by deepaklalwani97** [comment]
@juhi123 I have Self-tested this issue with the latest version of the PWA plugin. Can you perform a QA test round with the `fix/gh-41` branch and check whether it fixes the issue.

**Comment by juhi123** [comment]
@deepaklalwani97 I have tested all test [cases](https://docs.google.com/spreadsheets/d/1Yx3D2XSlucnl5G_P3tbAxsDCQUGNV7NIhZkA6f2UVJU/edit#gid=664431186), looks fine now.

**Comment by deepaklalwani97** [comment]
Thanks @juhi123 for the update.
