### ISSUE TITLE
[PWA] Disable workbox console messages 

### ISSUE THREAD

**Issue by pradeep910** [rtCamp/pwa-extension#5]
Workbox use `WP_DEBUG` constant to detect `Dev` or `Prod`. So if we have `WP_DEBUG` log true and `WP_DEBUG_DISPLAY` as `false`, it will log errors/messages in console by default.

![Screenshot 2019-12-23 at 6 57 40 PM](https://user-images.githubusercontent.com/1139853/71360506-2009a500-25b6-11ea-8a71-ce1e2b490946.png)

https://github.com/GoogleChrome/workbox/blob/6845f53c0053a4f162475d678bbd7a9e385b53d0/packages/workbox-core/src/_private/logger.ts#L24

Need to inject this script in the service worker through PWA plugin filters. As specified here - https://github.com/GoogleChrome/workbox/pull/2296
 
`self.__WB_DISABLE_DEV_LOGS = self.__WB_DISABLE_DEV_LOGS || false;`

**Comment by deepaklalwani97** [comment]
The `self.__WB_DISABLE_DEV_LOGS` constant check for disabling logs is available from the 5.0 workbox version and the PWA plugin currently uses 4.3.1. So adding this constant in the service worker will not work until the workbox version is updated in the PWA plugin.

**Comment by deepaklalwani41** [comment]
The version of workbox is updated in the alpha version of the PWA plugin. I have tested on that alpha version and adding `self.__WB_DISABLE_DEV_LOGS = true;` disables the workbox logs properly.

**Comment by deepaklalwani97** [comment]
The version of workbox is updated in the alpha version of the PWA plugin. I have tested on that alpha version and adding self.__WB_DISABLE_DEV_LOGS = true; disables the workbox logs properly.

**Comment by deepaklalwani97** [comment]
PR for this issue blocked because of https://github.com/rtCamp/pwa-extension/pull/6#issuecomment-568725310

**Comment by pradeep910** [comment]
This we will keep open until the Workbox updates to latest version in PWA plugin. 
In blocked status.

**Comment by deepaklalwani97** [comment]
The latest version of PWA by default disables the dev logs and Setting `WP_SERVICE_WORKER_DEBUG_LOG`  to true enables the dev log. So no code change is required in our plugin and this issue can be closed.
CC:- @pradeep910 @DevikVekariya

**Comment by pradeep910** [comment]
Correct. Closing this as new release of PWA plugin has latest Workbox JS which solves this issue.
