### ISSUE TITLE
[PWA] Offline Google Analytics

### ISSUE THREAD

**Issue by pradeep910** [rtCamp/pwa-extension#7]
Refer - https://developers.google.com/web/ilt/pwa/integrating-analytics

**Comment by pradeep910** [comment]
@deepaklalwani97 

I tried offline surfing on https://rtcamp-v9.dev3.rt.gw/ and it seems like background sync is being used for `offline analytics events`.

You can test this by `recording Background Sync`

![Screenshot 2019-12-25 at 5 03 50 PM](https://user-images.githubusercontent.com/1139853/71444624-c1206900-2738-11ea-95e1-a39a3ad14625.png)

On Analytics it will show in custom reports as I have added it under `dimension4 (cd4)`.

```
workbox.googleAnalytics.initialize({
  parameterOverrides: {
    cd4: "offline",
  },
});
```

https://analytics.google.com/analytics/web/#/my-reports/1koAhX7ZSo627cIck84quw/a45690541w76431964p79014466/_u.date00=20191225&_u.date01=20191225/

![Screenshot 2019-12-25 at 5 06 39 PM](https://user-images.githubusercontent.com/1139853/71444665-10669980-2739-11ea-9ae8-e80856df30f9.png)

cc @chandrapatel @umeshnevase

**Comment by deepaklalwani97** [comment]
Yes, I tested that by recording background sync activity it makes requests and internet is available.

**Comment by deepaklalwani97** [comment]
@pradeep910 Can we close this issue?

**Comment by pradeep910** [comment]
Yes I think we can close.
